#!/usr/bin/env bash
# Domain zone so that the subdomain www points to your load-balancer IP lb-01

website=$1
sub=$2

function meow_func () {
    for subs; do
        meow=$(dig $subs.$website | grep -A1 'ANSWER SECTION:' | tail -1);
        record=$(echo $meow | awk '{print$4}');
        ip=$(echo $meow | awk '{print$5}');
        echo The subdomain $subs is a $record record and points to $ip;
        done
}

# when there is sub passed in
if [ $# -eq 2 ]; then 
    meow=$(dig $sub.$website | grep -A1 'ANSWER SECTION:' | tail -1);
    record=$(echo $meow | awk '{print$4}');
    ip=$(echo $meow | awk '{print$5}');
    echo The subdomain $subs is a $record record and points to $ip;

else
    meow_func 'www' 'lb-01' 'web-01' 'web-02';
fi

