#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# scp(secure copy)-o(ssh_option)Strict....=no(option passed to ssh)
# -i(identityfile)
# test -> scp -o StrictHostKeyChecking=no -i ~/.ssh/holberton meow1
# ubuntu@34.75.36.193:~/


if [[ $# -ne 4 ]]; then
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY;
else 
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/;
fi
