#!/usr/bin/env bash
# install nginx on server

apt-get update
apt-get -y install nginx
#ufw allow 'Nginx HTTP'
echo "Holberton School" | tee /var/www/html/index.html
#cp /etc/nginx/sites-available/default_save /etc/nginx/sites-available/default
service nginx restart
