#!/usr/bin/env bash
# install nginx on server
apt-get update
apt-get -y install nginx
#ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html

file=~/bre_conf
conf="server {
 			  listen 80 default_server;
 			  listen [::]:80 default_server;
 			  root /etc/nginx/html;
 			  root /var/www/html;
 			  index index.html index.htm;
  			  location /redirect_me {
  			    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
 			 }
	  }"

touch "$file" && chmod +w "$file"
echo "$conf" > "$file"
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_save;
sudo cp "$file" /etc/nginx/sites-available/default;
service nginx restart;