#!/usr/bin/env bash
# install nginx on server

apt-get -y update;
apt-get -y install nginx;
echo Holberton School | sudo tee /var/www/html/index.html;
#scp -i ~/.ssh/holberton -o StrictHostKeyChecking=no bre_conf ubuntu@34.75.36.193:~/;
conf="server {
	listen 80;
	listen [::]:80 default_server;

	root /usr/share/nginx/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}"
echo "$conf" > bre_conf
sudo cp bre_conf /etc/nginx/sites-available/default;

service nginx restart;
