#!/usr/bin/env bash
# install nginx on server

apt-get update
apt-get -y install nginx
#ufw allow 'Nginx HTTP'

touch /var/www/html/404.html && chmod +w /var/www/html/404.html
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

file=/etc/nginx/sites-available/default
confFile=~/bre_conf

conf="server {
 			  listen 80 default_server;
 			  listen [::]:80 default_server;
 			  root /var/www/html;
 			  index index.html index.htm;
  			  location /redirect_me {
  			    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
 			  }
              error_page 404 /404.html;
              location = /404.html {
                internal;
              }
	  }"
touch "$confFile" && chmod +w "$file"
echo "$conf" > "$confFile"
sudo cp "$confFile" "$file";
service nginx restart;
