#!/usr/bin/env bash
# install nginx on server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
file=/etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" "$file"
sed -i "/listen 80 default_server/a error_page 404 /404/html;" "$file"
service nginx restart;
