#!/usr/bin/env bash                                
# configure web-02 to be identical to web-01       

apt-get update                                    
apt-get -y install nginx                          

file=~/bre_conf
defConf=/etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "server {
              add_header X-Served-By $HOSTNAME;
 			  listen 80 default_server;
 			  listen [::]:80 default_server;
 			  root /var/www/html;
 			  index index.html index.htm index.nginx-debian.html;
			  server_name _;
  			  location /redirect_me {
  			    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
 			 }
              error_page 404 /404.html;
	  }" | tee "$file";

sudo cp "$file" "$defConf"
sudo service nginx restart;
