#!/usr/bin/env bash
# Debugging Nginx installation from listening on port 80
apt-get update && apt-get -y install nginx
sudo rm /etc/nginx/sites-enabled/default && sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default 
sudo service nginx restart && sudo /usr/sbin/nginx -s stop
