#!/usr/bin/env bash
# script to display nums 1 - 100. "Fizz" on mult of 3. "Buzz" on mult of 5. "FizzBuzz" on mults of 3 & 5
x=0
while [ $((x++)) -le 99 ]; do
	if ! ((x%15)); then echo "FizzBuzz";
	elif ! ((x%3)); then echo "Fizz";
	elif ! ((x%5)); then echo "Buzz"; else echo "$x"; fi; done
