#!/usr/bin/env bash
# This script diplays numbers 1 - 20. Bad lucks after lines 4, 9 and 17

x=0
while [ $((x++)) -le 19 ]
do
	echo "$x"

	case "$x" in

		4) echo "bad luck from China"
	   	   ;;
		
		9) echo "bad luck from Japan"
	       ;;

		17) echo "bad luck from Italy"
	        ;;
esac
done