#!/usr/bin/env bash
# script to display file information about holbertonschool

x="holbertonschool"

if [ ! -e $x ]; then echo "$x file does not exist"; else echo "{$x} file exists";
	
if [ ! -s $x ]; then echo "$x file is empty"; else echo "{$x} file is not empty"; fi

if [ -f $x ]; then echo "$x is a regular file"; fi; fi
