#!/usr/bin/env bash
# script that configures an Ubuntu server

TEST="/home/vagrant/holberton-system_engineering-devops/0x08-networking_basics_2/test"

cat /etc/hosts > $TEST
sed -i s/127.0.0.1/127.0.0.2/ $TEST
echo '8.8.8.8   facebook.com' >> $TEST
cat $TEST > /etc/hosts
rm -f $TEST
