#!/usr/bin/env bash
# install nginx on server

sudo apt-get update;
sudo apt-get -y install apache2;
apt-get update;
apt-get -y install nginx;
sudo service apache2 start;
sudo pkill -f apache2;
sudo chmod 664 /etc/nginx/nginx.conf;
sudo chown nginx:nginx /etc/nginx/nginx.conf;

file=~/bre_conf;
conf="server {
    add_header X-Served-By $HOSTNAME;
    listen 8080 default_server;
    listen [::]:8080 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location /hbnb_static {
      alias /data/web_static/current/;
                index index.html index.htm;
   }

    error_page 404 /404.html;
}"
echo "$conf" > "$file"
sudo cp "$file" /etc/nginx/sites-available/default;
sudo -u nginx service nginx restart;
