#!/usr/bin/env bash
# install nginx on server

sudo apt-get update;
sudo apt-get -y install apache2;
sudo service apache2 start;
sudo pkill -f apache2;
sudo chmod 664 /etc/nginx/nginx.conf;
sudo chown nginx:nginx /etc/nginx/nginx.conf;
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default;
sudo -u nginx service nginx restart;
