#!/usr/bin/env bash
# run as nginx user

sudo pkill -f apache2;
sudo chmod 700 /etc/nginx/nginx.conf;
sudo chown nginx:nginx /etc/nginx/nginx.conf;
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default;
sudo -u nginx service nginx restart;
